version: 2
project_name: todomd

builds:
  - main: .
    binary: todomd
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/walm/todomd/internal/cli.version=v{{ .Version }}

archives:
  - name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: checksums.txt

changelog:
  use: git
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  draft: false
